services:
  postgres:
    container_name: postgres
    image: postgres:${POSTGRESS_TAG:-latest}
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - volume_docker_pg:/var/lib/postgresql/data
    networks:
      - kube_news_net

  kube_news_web:
    container_name: kube_news_web
    image: fspelling/kube-news:${KUBE_NEWS_TAG:-latest}
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DB_DATABASE=${POSTGRES_DB} 
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=postgres
    depends_on:
      - postgres
    networks:
      - kube_news_net

volumes:
  volume_docker_pg:
    name: volume_docker_pg

networks:
  kube_news_net:
    name: kube_news_net
    driver: bridge