services:
  kube_news_web:
    container_name: kube_news_web
    image: fspelling/kube-news:${KUBE_NEWS_TAG:-latest}
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DB_DATABASE=${POSTGRES_DB} 
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=postgres
    depends_on:
      - postgres
    networks:
      - kube_news_net